# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Makecli < Formula
  desc "makecli — agentic development platform cli"
  homepage "https://github.com/qfeius/makecli"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/qfeius/makecli/releases/download/v0.2.1/makecli_0.2.1_darwin_amd64.tar.gz"
      sha256 "aff4ffe823e5f2aaba87e20b48af5c9cc315f4717ea3d0c525f51a1824ba5de1"

      define_method(:install) do
        bin.install "makecli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/qfeius/makecli/releases/download/v0.2.1/makecli_0.2.1_darwin_arm64.tar.gz"
      sha256 "6145c81f76e512c2e9d3d955f498f182451faf80ec91bb477ac99de16e4d9ee6"

      define_method(:install) do
        bin.install "makecli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/qfeius/makecli/releases/download/v0.2.1/makecli_0.2.1_linux_amd64.tar.gz"
      sha256 "50109fba580d7aa31bc0fe33b0ea3eb7f24e49e6e17e36be8eeed7dad51a18cc"
      define_method(:install) do
        bin.install "makecli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/qfeius/makecli/releases/download/v0.2.1/makecli_0.2.1_linux_arm64.tar.gz"
      sha256 "6f3dbdad7eb91816916b9174004037a8f037a2a10826650f0472fb59aaa46582"
      define_method(:install) do
        bin.install "makecli"
      end
    end
  end

  test do
    system "#{bin}/makecli version"
  end
end
