# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Makecli < Formula
  desc "makecli — agentic development platform cli"
  homepage "https://github.com/qfeius/makecli"
  version "0.1.13"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/qfeius/makecli/releases/download/v0.1.13/makecli_0.1.13_darwin_amd64.tar.gz"
      sha256 "4488073e85aa3e744684e1ed6c55019244ab30c6a8696ccaef08f2d033355fc8"

      define_method(:install) do
        bin.install "makecli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/qfeius/makecli/releases/download/v0.1.13/makecli_0.1.13_darwin_arm64.tar.gz"
      sha256 "ce736606851dee286bcc0bc9b8500dbfe113b728a6afd3ccc5d1fd3962d02d16"

      define_method(:install) do
        bin.install "makecli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/qfeius/makecli/releases/download/v0.1.13/makecli_0.1.13_linux_amd64.tar.gz"
      sha256 "18d5c03eaf4b2527321efdbe763359989a95c2d8ba5cc3d84f43d9fab5d6b386"
      define_method(:install) do
        bin.install "makecli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/qfeius/makecli/releases/download/v0.1.13/makecli_0.1.13_linux_arm64.tar.gz"
      sha256 "cab0b2e04cc7ce0e079b5fe09d7b0ab6bbb442fad6f0f2dcab0a9fe57a49a86e"
      define_method(:install) do
        bin.install "makecli"
      end
    end
  end

  test do
    system "#{bin}/makecli version"
  end
end
