# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Makecli < Formula
  desc "makecli — agentic development platform cli"
  homepage "https://github.com/MakeHQ/makecli"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MakeHQ/makecli/releases/download/v0.1.7/makecli_0.1.7_darwin_amd64.tar.gz"
      sha256 "686cf681c3564b2dae4622292eeb157fc69c242abb7a2ad1c6fec981202417d2"

      define_method(:install) do
        bin.install "makecli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MakeHQ/makecli/releases/download/v0.1.7/makecli_0.1.7_darwin_arm64.tar.gz"
      sha256 "009f57c348e818b30db2afa71f59e05c6b25a5fd3b5beef735005c56aa799457"

      define_method(:install) do
        bin.install "makecli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MakeHQ/makecli/releases/download/v0.1.7/makecli_0.1.7_linux_amd64.tar.gz"
      sha256 "6395351c7f35591e79f35d3a4067419c00eecea82a8ea3212e7f5349540d83eb"
      define_method(:install) do
        bin.install "makecli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MakeHQ/makecli/releases/download/v0.1.7/makecli_0.1.7_linux_arm64.tar.gz"
      sha256 "896a5cf0489fd12c45ea95179fd3608d38d5dcabb36ad8d1a70c0e222aa9a313"
      define_method(:install) do
        bin.install "makecli"
      end
    end
  end

  test do
    system "#{bin}/makecli version"
  end
end
